config/routes.rb
BusK::Application.routes.draw do
  devise_for :users
  get "/sobre" => 'application#about', as: :about
  resources :busstops

  get '/linhas' => 'lines#all_lines', as: :all_lines
  resources :lines do
    resources :returns
    resources :goings
  end
  match 'search' => 'searches#index', as: :search, via: [:get, :post]
  get '/lines/:id/routes' => 'lines#routes', as: :routes

  root :to => 'welcomes#index'
end

app/models/line.rb
class Line < ActiveRecord::Base
  has_many :goings
  has_many :returns

  # def self.search
  #   @line = Line.where("")
  # end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy, :routes]
  before_filter :authenticate_user!, except: [:all_lines, :show]
  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
    @line = Line.new
  end

  def all_lines
    @lines = Line.all
    @lines_count = Line.distinct.count(:include => :goings) + Line.distinct.count(:include => :returns)
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
    @goings = @line.goings
    @returns = @line.returns
    @days = {"Dom" => "D", "Seg" => "S", "Ter" => "T", "Qua" => "Q", "Qui" => "Q", "Sex" => "S", "Sab" => "S"}
  end

  # GET /lines/1/edit
  def edit
    @going = @line.goings.new
    @return = @line.returns.new
  end

  def routes
    @going = @line.goings.new
    @return = @line.returns.new
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to new_line_going_path(@line), notice: 'Linha criada com sucesso.' }
        format.json { render action: 'edit', status: :created, location: @line }
      else
        format.html { render action: 'index' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Linha atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:name)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line, :html => {:class => "line_form"}) do |f| %>
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field name">
    <%= f.label :name, 'Nome' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar linha' %>
  </div>
<% end %>

app/views/lines/_maps.html.erb
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDc7y0hbNmHzHKgaqe7VCl6a--P4VAW2lU&sensor=false">
</script>

app/views/lines/_search.html.erb
<h1>BusK</h1>

<%= form_for (search_path), method: :get do |f| -%>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "enviar", name: nil %>
  </div>
<% end -%>

app/views/lines/all_lines.html.erb
<div class="hl_top_content hl_content">
  <h1>Linhas</h1>
</div>

<div class="container">
  <div class="center_panel tb_panel">
    <table class="tb_lines">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Nº rotas</th>
        </tr>
      </thead>

      <tbody>
        <% @lines.each do |line| %>
          <tr>
            <td class="name"><%= link_to line.name, line %></td>
            <td class="start_time"><%= @lines_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/lines/edit.html.erb
<div class="full_window">
  <div class="center_panel">
    <div class="content">
      <h1 class="center_alg">Editar <%= @line.name %></h1>
      <%= render 'form' %>
    </div>
  </div>

  <div class="static">
    <img src="http://maps.google.com/maps/api/staticmap?center=Palmas,TO&zoom=12&size=1024x1024&maptype=roadmap&sensor=false&scale=4">
  </div>
</div>

app/views/lines/index.html.erb
<div class="hl_top_content hl_content">
  <h1>Linhas</h1>
</div>

<div class="container">
  <div class="panel tb_panel">
    <table class="tb_lines">
      <thead>
        <tr>
          <th>Nome</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @lines.each do |line| %>
          <tr>
            <td class="name"><%= link_to line.name, line %></td>
            <td class="actions"><%= link_to image_tag('edit.png'), edit_line_path(line), alt: 'Editar', title: 'Editar' %>
                <%= link_to image_tag('remove.png'), line, method: :delete, data: { confirm: 'Are you sure?' }, alt: 'Editar', title: 'Editar' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="new_panel">
    <h2>Nova linha</h2>
      <%= render 'form' %>
  </div>
</div>

app/views/lines/new.html.erb
<div class="full_window">
  <div class="center_panel">
    <div class="content">

    </div>
  </div>



  <div class="static">
    <img src="http://maps.google.com/maps/api/staticmap?center=Palmas,TO&zoom=12&size=1024x1024&maptype=roadmap&sensor=false&scale=4">
  </div>
</div>

app/views/lines/routes.html.erb
<%= content_for :head do %>
  <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAycpplL-OwuIip9fyTMyO6pxVYl1eMi5Y&sensor=true">
    </script>
<% end %>

app/views/lines/show.html.erb
<div class="hl_top_content hl_content">
  <h1><%= @line.name %></h1>
  <%= content_for :settings do %>
    <div class="route_actions">
      <ul>
        <li><%= link_to 'Editar linha', edit_line_path(@line) %></li>
        <li><%= link_to 'Adicionar ida', new_line_going_path(@line) %></li>
        <li><%= link_to 'Adicionar volta', new_line_return_path(@line) %></li>
      </ul>
  </div>
  <% end %>
</div>

<div class="going_line">
<h2>Idas</h2>
<% @goings.each do |going| %>
  <a href="<%= line_going_path(going.line_id, going.id) %>" class="route">
    <nav class="week">
      <% @days.each do |i, d| %>
        <% if going.days_of_week.split(',').include? i %>
          <li class="day selected"><%= d %></li>
        <% else %>
          <li class="day"><%= d %></li>
        <% end %>
      <% end %>
    </nav>
    <div class="route_name"><span><%= truncate going.line.name, length: 15 %></span></div>
  </a>
<% end %>
</div>

<div class="return_line">
  <h2>Voltas</h2>
  <% @returns.each do |r| %>
    <a href="<%= line_return_path(r.line_id, r.id) %>" title="<%= r.line.name %>" class="route">
      <nav class="week">
        <% @days.each do |i, d| %>
          <% if r.days_of_week.split(',').include? i %>
          <li class="day selected"><%= d %></li>
          <% else %>
            <li class="day"><%= d %></li>
          <% end %>
        <% end %>
      </nav>
      <div class="route_name"><span><%= truncate r.line.name, length: 15 %></span></div>
    </a>
  <% end %>
</div>