config/routes.rb
BusK::Application.routes.draw do
  devise_for :users
  get "/sobre" => 'application#about', as: :about
  resources :busstops

  get '/linhas' => 'lines#all_lines', as: :all_lines
  resources :lines do
    resources :returns
    resources :goings
  end
  match 'search' => 'searches#index', as: :search, via: [:get, :post]
  get '/lines/:id/routes' => 'lines#routes', as: :routes

  root :to => 'welcomes#index'
end

app/models/busstop.rb
class Busstop < ActiveRecord::Base
  validates_presence_of :kind, message: "Tipo não foi escolhido"
  validates_presence_of :lat, message: "A localização não foi determinada"
  validates_presence_of :lng
end

app/controllers/busstops_controller.rb
class BusstopsController < ApplicationController
  before_action :set_busstop, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /busstops
  # GET /busstops.json
  def index
    @busstops = Busstop.all
    @busstop = Busstop.new
  end

  # GET /busstops/1
  # GET /busstops/1.json
  def show
  end

  # GET /busstops/new
  def new
    @busstop = Busstop.new
  end

  # GET /busstops/1/edit
  def edit
  end

  # POST /busstops
  # POST /busstops.json
  def create
    @busstop = Busstop.new(busstop_params)

    respond_to do |format|
      if @busstop.save
        format.html { redirect_to busstops_path, notice: 'Parada salva com sucesso.' }
        format.json { render action: 'index', status: :created, location: @busstop }
      else
        format.html { render action: 'new' }
        format.json { render json: @busstop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /busstops/1
  # PATCH/PUT /busstops/1.json
  def update
    respond_to do |format|
      if @busstop.update(busstop_params)
        format.html { redirect_to busstops_path, notice: 'Busstop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @busstop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busstops/1
  # DELETE /busstops/1.json
  def destroy
    @busstop.destroy
    respond_to do |format|
      format.html { redirect_to busstops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busstop
      @busstop = Busstop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def busstop_params
      params.require(:busstop).permit(:name, :lat, :lng, :kind)
    end
end

app/helpers/busstops_helper.rb
module BusstopsHelper
end

app/views/busstops/_form.html.erb
<%= form_for(@busstop, :html => {:class => 'busstop_form'}) do |f| %>
  <% if @busstop.errors.any? %>
    <div id="error_explanation">
      <h2>Alguma coisa deu errado. Veja o que ocorreu:</h2>

      <ul>
      <% @busstop.errors.full_messages.each do |i, msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <div class="field">
    <%= f.label :name, 'Nome' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind, 'Tipo' %><br>
    <%= f.select :kind, {0 => 'Parada', 1 => 'Estação'}.map{|i, v| [v, i]} %>
  </div>
  <div class="actions">
    <%= f.submit params[:action] == 'new' ? 'Salvar parada' : 'Atualiza parada' %>
  </div>
<% end %>

app/views/busstops/edit.html.erb
<div class="sidebar">
  <div class="content">
    <h1>Editar parada</h1>
    <%= render 'form' %>
  </div>
</div>
<div class="main_window">
  <div class="map">
    <div id="map-canvas"/>
  </div>
</div>

<%= content_for :foot do %>
  <%= render 'lines/maps' %>
  <%= javascript_include_tag 'bs_map', :cache => true %>
  <script>
  $(document).ready(function() {
    initialize(true, <%= @busstop.lat %>, <%= @busstop.lng %>, "<%= @busstop.name %>");
  })
  </script>
<% end %>

app/views/busstops/index.html.erb
<%= content_for :settings do %>
<div class="route_actions">
  <ul>
    <li><%= link_to 'Adicionar parada', new_busstop_path %></li>
  </ul>
</div>
<% end %>
<div class="hl_top_content hl_content">
  <h1>Paradas/Estações</h1>
</div>

<div class="container">
  <div class="center_panel tb_center_panel">
    <table class="tb_busstops">
      <thead>
        <tr>
          <th>Nome</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @busstops.each do |busstop| %>
          <tr>
            <td class="name"><div class="bus_icon"><%= busstop.kind == 1 ? image_tag('busstation.png') : image_tag('busstop.png') %></div><%= link_to busstop.name, busstop %></td>
            <td class="actions"><%= link_to image_tag('edit.png'), edit_busstop_path(busstop), alt: 'Editar', title: 'Editar' %>
                <%= link_to image_tag('remove.png'), busstop, method: :delete, data: { confirm: 'Deseja realmente remover?' }, alt: 'Remover', title: 'Remover', id: 'delete_busstop' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/busstops/new.html.erb
<div class="sidebar">
  <div class="content">
    <h1>Nova parada</h1>
    <%= render 'form' %>
  </div>
</div>
<div class="main_window">
  <div class="map">
    <div id="map-canvas"/>
  </div>
</div>

<%= content_for :foot do %>
  <%= render 'lines/maps' %>
  <%= javascript_include_tag 'bs_map', :cache => true %>
  <script>
  $(document).ready(function() {
    initialize(false);
  })
  </script>
<% end %>

app/views/busstops/show.html.erb
<%= content_for :settings do %>
  <div class="route_actions">
    <ul>
      <li><%= link_to 'Editar', edit_busstop_path(@busstop) %></li>
    </ul>
  </div>
<% end %>
<div class="hl_top_content hl_content"><h1><%= @busstop.name %></h1></div>
<div class="full_window">
  <div class="map">
    <div id="map-canvas"/>
  </div>
</div>

<%= content_for :foot do %>
  <%= render 'lines/maps' %>
  <%= javascript_include_tag 'bs_map', :cache => false %>
  <script>
  $(document).ready(function() {
    initialize(false, <%= @busstop.lat %>, <%= @busstop.lng %>, "<%= @busstop.name %>");
  })
  </script>
<% end %>