config/routes.rb
BusK::Application.routes.draw do
  devise_for :users
  get "/sobre" => 'application#about', as: :about
  resources :busstops

  get '/linhas' => 'lines#all_lines', as: :all_lines
  resources :lines do
    resources :returns
    resources :goings
  end
  match 'search' => 'searches#index', as: :search, via: [:get, :post]
  get '/lines/:id/routes' => 'lines#routes', as: :routes

  root :to => 'welcomes#index'
end

app/models/return.rb
class Return < ActiveRecord::Base
  belongs_to :line
  def self.search(cur_b, des_b)
    if cur_b != " " && des_b != " "
      where('blocks_passed LIKE ? AND blocks_passed LIKE ?', "%#{cur_b}%", "%#{des_b}%")
    else
      return []
    end
  end

  def self.search_surroundings(cur_b, des_b)
    where('surroundings LIKE ? AND surroundings LIKE ?', "%#{cur_b}%", "%#{des_b}%")
  end

end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :set_return, only: [:show, :edit, :update, :destroy]
  before_action :set_line
  before_filter :authenticate_user!, except: [:show]

  # GET /returns/1
  # GET /returns/1.json
  def show
    @blocks_passed = @return.blocks_passed.split(",")
    @bs = Busstop.all
    @busstops = @bs.map { |b| [b.lat.to_f, b.lng.to_f, b.kind.to_i] }
    @start_time = @return.schedule.split(",")[0]
    @end_time = @return.schedule.split(",")[@return.schedule.split(",").length - 1]
  end

  # GET /returns/new
  def new
    if params[:g_id]
      @going = Going.find(params[:g_id])
      @return = Return.new(:blocks_passed => @going.blocks_passed, :days_of_week => @going.days_of_week)
    else
      @return = Return.new
    end
    @days = {"Dom" => "D", "Seg" => "S", "Ter" => "T", "Qua" => "Q", "Qui" => "Q", "Sex" => "S", "Sab" => "S"}
  end

  # GET /returns/1/edit
  def edit
    @days = {"Dom" => "D", "Seg" => "S", "Ter" => "T", "Qua" => "Q", "Qui" => "Q", "Sex" => "S", "Sab" => "S"}
  end

  # POST /returns
  # POST /returns.json
  def create
    @return = Return.new(return_params)

    respond_to do |format|
      if @return.save
        format.html { redirect_to @line, notice: 'Return was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line }
      else
        format.html { render action: 'new' }
        format.json { render json: @return.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /returns/1
  # PATCH/PUT /returns/1.json
  def update
    respond_to do |format|
      if @return.update(return_params)
        format.html { redirect_to line_return_path(@return.line_id, @return), notice: 'Return was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @return.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /returns/1
  # DELETE /returns/1.json
  def destroy
    @return.destroy
    respond_to do |format|
      format.html { redirect_to line_path(@return.line_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_return
      @return = Return.find(params[:id])
    end

    def set_line
      @line = Line.find(params[:line_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def return_params
      params.require(:return).permit(:start_location, :end_location, :waypoints, :blocks_passed, :downvotes, :line_id, :days_of_week, :frequency, :schedule)
    end
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/views/returns/_form.html.erb
<%= form_for([@line, @return], :html => {:class => 'return_form'}) do |f| %>
  <% if @return.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@return.errors.count, "error") %> prohibited this return from being saved:</h2>

      <ul>
      <% @return.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :start_location %>
  <%= f.hidden_field :end_location %>
  <%= f.hidden_field :waypoints %>
  <div class="field">
    <%= f.label :frequency, 'Frequência' %> <br>
    <%= f.number_field :frequency, autofocus: true %>(min)
  </div>
  <div class="field days_of_week">
    <%= f.label :days_of_week, 'Dias da semana' %>
    <%= f.hidden_field :days_of_week %>
    <div class="week">
      <% if params[:action] == 'edit' %>
      <ul>
      <% @days.each do |i, d| %>
        <% if @return.days_of_week.split(',').include? i %>
          <li class="day selected"><%= i %></li>
        <% else %>
          <li class="day"><%= i %></li>
        <% end %>
      <% end %>
      </ul>
    <% else %>
      <ul>
        <li class="day">Dom</li>
        <li class="day">Seg</li>
        <li class="day">Ter</li>
        <li class="day">Qua</li>
        <li class="day">Qui</li>
        <li class="day">Sex</li>
        <li class="day">Sab</li>
      </ul>
    <% end %>
    </div>
  </div>
  <div class="field">
    <%= f.label :blocks_passed, "Quadras por onde passa" %><br>
    <%= f.text_area :blocks_passed %>
  </div>
  <%= f.hidden_field :line_id, value: @line.id %>
  <div class="actions">
    <%= f.submit "Salvar Volta", id: :save_return %>
  </div>
<% end %>

app/views/returns/edit.html.erb
<div class="sidebar">
  <div class="content">
    <h1>Editar <%= @line.name %> - Volta</h1>
    <%= render 'form' %>
  </div>
</div>
<div class="main_window">
  <div class="map">
    <div id="map-canvas"/>
  </div>
</div>
<%= content_for :foot do %>
  <%= render 'lines/maps' %>
  <%= javascript_include_tag 'l_map', :cache => true %>
  <script>
  $( document ).ready(function() {
    initialize(true);
    loadRoute(<%= raw '{"start":{"lat":'+@return.start_location.split(",")[0].to_s+',"lng":'+@return.start_location.split(",")[1].to_s+'},"end":{"lat":'+@return.end_location.split(",")[0].to_s+',"lng":'+@return.end_location.split(",")[1].to_s+'},"waypoints":'+@return.waypoints.to_s+'}' %>);
  });
  </script>
<% end %>

app/views/returns/new.html.erb
<div class="sidebar">
  <div class="content">
    <h1><%= @line.name %> - Volta</h1>
    <%= render 'form' %>
  </div>
</div>
<div class="main_window">
  <div class="map">
    <div id="map-canvas"/>
  </div>
</div>
<%= content_for :foot do %>
  <%= render 'lines/maps' %>
  <%= javascript_include_tag 'l_map', :cache => true %>
  <script>
  $( document ).ready(function() {
    initialize(true);
    calcRoute();
  })
  </script>
<% end %>

app/views/returns/show.html.erb
<% content_for :settings do %>
  <div class="route_actions">
    <ul>
      <li><%= link_to 'Editar rota', edit_line_return_path(@line, @return) %></li>
      <li><%= link_to 'Voltar', @line %></li>
    </ul>
  </div>
<% end %>
<div class="sidebar">
  <div class="content">
    <h1><%= @return.line.name %> - Volta</h1>
    <div class="left_alg box_100pc">
      <h3>Intinerário:</h3>
      <p class="l_time">
        <strong>Início:</strong>
        <%= @start_time %>
      </p>
      <p class="l_time">
        <strong>Fim:</strong>
        <%= @end_time %>
      </p>
    </div>
    <div class="blocks_passed">
      <h3>Esta linha passa por:</h3>
      <ul>
        <% @blocks_passed.each do |b| %>
        <li><%= b %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="main_window">
  <div class="map">
    <div id="map-canvas"/>
  </div>
</div>
<%= content_for :foot do %>
  <%= render 'lines/maps' %>
  <%= javascript_include_tag 'l_map', :cache => true %>
  <script>
  $( document ).ready(function() {
    initialize(false, <%= raw @busstops %>,[<%= @return.start_location.split(",")[0].to_s+','+@return.start_location.split(",")[1].to_s %>], [<%= @return.end_location.split(",")[0].to_s+','+@return.end_location.split(",")[1].to_s%>]);
    loadRoute(<%= raw '{"start":{"lat":'+@return.start_location.split(",")[0].to_s+',"lng":'+@return.start_location.split(",")[1].to_s+'},"end":{"lat":'+@return.end_location.split(",")[0].to_s+',"lng":'+@return.end_location.split(",")[1].to_s+'},"waypoints":'+@return.waypoints.to_s+'}' %>);
  });
  </script>
<% end %>