config/routes.rb
BusK::Application.routes.draw do
  devise_for :users
  get "/sobre" => 'application#about', as: :about
  resources :busstops

  get '/linhas' => 'lines#all_lines', as: :all_lines
  resources :lines do
    resources :returns
    resources :goings
  end
  match 'search' => 'searches#index', as: :search, via: [:get, :post]
  get '/lines/:id/routes' => 'lines#routes', as: :routes

  root :to => 'welcomes#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_menu.html.erb
<nav class="main_menu">
  <div class="menu_title"><span>MENU</span></div>
  <li><%= link_to 'Início', root_path %></li>
  <li><%= link_to 'Linhas', all_lines_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to 'Paradas', busstops_path %></li>
  <% end %>
  <li><%= link_to 'Sobre', about_path %></li>
  <div class="donate">

  </div>
</nav>

app/views/application/about.html.erb
<div class="container">
  <div class="content">
    <div class="panel tb_panel">
      <h1>Sobre o BusK</h1>

      <p>O BusK foi criado para ajudar pessoas como você que precisa usar o ônibus, mas não conhece todas as rotas. Nele, basta inserir onde você está e onde deseja ir que serão exibidas rotas que passam pelas quadras que você informou.</p>
      <br>
      <h2>Qual a diferença do BusK para os outros?</h2>
      <p>O BusK funciona em qualquer navegador, independente de sistema operacional, ou seja, em celulares, tablets, notebooks e desktops. Basta um navegador. Além disso, <strong>você não precisa conhecer as rotas</strong> para usar o BusK, assim, mesmo pessoas de outras cidades podem usá-lo sem dificuldades.</p>
    </div>
  </div>
</div>